### ISSUE TITLE
Can no longer create rooms on standard Hubs Cloud instance

### ISSUE THREAD

**Issue by Charlesc22** [mozilla/hubs-cloud#110]
Something got broken on the latest update. I can't even create a room anymore from the home page button. And previously created rooms no longer load.
The installation I have is standard. No custom client. I'm getting the following error:

![](https://cdn.discordapp.com/attachments/715710114438447114/754427455133057135/unknown.png)

This is the only error I see in the Dev>Network tab:

![](https://cdn.discordapp.com/attachments/715710114438447114/754427794326421535/unknown.png)

**Comment by Charlesc22** [comment]
Re-starting the Stack solved the problem. All rooms and "Create room" working again.
Things do seem to have broken during the last update though. other encountered the same problem I had and also had to update the stack to resolve the issue.

**Comment by robin-k-wilson** [comment]
Going to close this issue, as it's resolved by updating the stack.
