### ISSUE TITLE
Importing .spoke files in Spoke on Hubs cloud

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs-cloud#120]
When I import a .spoke file, all the original URLs are left.  So, I have a bunch of content still being served from reticulum (if I exported from HMC), or links to URLs on other Hubs Cloud instances (if I loaded from there).

I don't think we want to automatically copy content over (for all kinds of reasons, like "I don't have permission to host this myself").

What would be REALLY useful is to have a button in Spoke, beside each URL (for images, models, or anything else that isn't a web page or streaming video URL) that says "Copy that asset here and fix the URL" (and when that's done, have it check for other references to that same URL in the project)

**Comment by robin-k-wilson** [comment]
I'm afraid Spoke intentionally points to external urls for assets so we're likely not going to implement this feature. You can update the url yourself by downloading the asset then importing it into your spoke. 

Thanks for making the feature request, you've started the conversation!
