### ISSUE TITLE
'Delete' button on 'Scenes' page won't delete selected scenes

### ISSUE THREAD

**Issue by BonzoMartini** [mozilla/hubs-cloud#127]
I have several scenes that are all old copies I want to get rid of and never see again.
In the Scene window selecting them either individually or severally and pressing 'Delete' trashcan button takes me to the signin screen however I'm already signed in. Going to 'Admin' button then 'Scenes' again shows me that the scene is still there. However the scene cannot be opened from the open link box icon. 

Similar behaviour in the Projects Window, selecting a project and hitting delete same thing

Expected behaviour =  hitting delete removes scenes/projects from the list

**Comment by robin-k-wilson** [comment]
Duplicate: https://github.com/mozilla/hubs/discussions/3142

Open issues to follow
Delete Accounts: mozilla/hubs-cloud#79
Delete scenes/accounts: mozilla/hubs-cloud#44 #2314

Relevant discussions
Managing users: #2747
