### ISSUE TITLE
Teleport to other user/moderator

### ISSUE THREAD

**Issue by cvisl** [mozilla/hubs-cloud#157]
When a room is especially large and a moderator is giving a tour through a room there are some situations that a user can get lost in the room. In this case it would be very usefull for that user to teleport to the tour guide of that room. Otherwise the user would miss out on the tour because of the spatial audio.

**Comment by misslivirose** [comment]
This is captured in https://github.com/mozilla/hubs/issues/3733 - closing this as a duplicate. Thanks for suggesting!
