### ISSUE TITLE
Templates on Spoke do not load correctly

### ISSUE THREAD

**Issue by yuriaru** [mozilla/hubs-cloud#17]
Project templates such as Moz Atrium and Club Hub do not load correctly when starting a new project. In the case of Moz Atrium, it seems that it loads Crafter instead; and for Club Hub just loads a black and white grid.

**Comment by misslivirose** [comment]
We've since changed and identified other issues with scene editor templates loading (https://github.com/mozilla/Spoke/issues/1082) so given the age of this issue I'm going to close and we'll track against the Spoke version of this bug.
