### ISSUE TITLE
Add room description

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs-cloud#21]
Rooms can have names, but for instances where the rooms are constructed with specific purposes and uses, they should have descriptions.

When we add room descriptions, they would somehow be incorporated on the homepage when those rooms appear (either due to favoriting or those rooms being public)

Also, if an API is made available to retrieve information about rooms (e.g., for #18), we'd want to retrieve the description.

**Comment by netpro2k** [comment]
Rooms can now have a description set in "Room Settings". Rooms with a description will show an info icon on the homepage, clicking it will bring up the room info dialog to view the description. 

https://github.com/mozilla/hubs/pull/2137
