### ISSUE TITLE
iFrame blocked by X-Frame-Options policy?

### ISSUE THREAD

**Issue by lachlanphillips** [mozilla/hubs-cloud#210]
As the topic suggests, the default policy (at least for enterprise) is to set X-Frame-Options to "sameorigin". 
Unsure if this is intended behaviour as Mozilla Hubs documentation refers to and encourages embedding into an iframe. 

Either way, is there a known workaround or method for changing this setting to allow specific, or all sites to embed?

Thanks

**Comment by rawnsley** [comment]
You can embed Hubs rooms as long as you include the embed code in the URL, which is unique to each room. I would actually like to disable this in my Hubs Cloud as well because I want all rooms to be embeddable by default so I'm interested to know if there's an easy way to do it.

**Comment by lachlanphillips** [comment]
Looks like there are ways to add header policy under server setup -> advanced. Should be able to set an X-Frame-Options policy there.
