### ISSUE TITLE
AWS room creation fails with "Unable to connect to this room"

### ISSUE THREAD

**Issue by MarcusMorba** [mozilla/hubs-cloud#219]
I just have set up a MozHubs Server (Personal) on AWS (latest version, recommended settings) and always now get this error:
"Unable to connect to this room, please try again later.
You can try connecting via TCP, which may work better on some networks.

You can also create a new room."

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1098)

**Comment by gdmtech** [comment]
Made clean install with template v1.1.2 and all good now

**Comment by MarcusMorba** [comment]
Is fixed
