### ISSUE TITLE
The room freezes when clicking the Connect to Twitter button 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs-cloud#228]
**[Affected Versions]:**
- Firefox Release 94.02
- Chrome 96
- Safari v15.1

**[Affected Platforms]:**
- Windows 10x64
- macOS BigSur v11.6.1
- Android 11

**[Prerequisites]:**
- Your Hubs Cloud stack is set up.
- Have a room opened in Hubs Cloud.
- The Twitter API keys are set up.

**[Steps to reproduce]:**
1. Take a photo or video using the Hubs camera.
2. Hover over the photo/video taken and click the Tweet button.
3. Click the Connect to Twitter button from the prompt displayed.
4. Observe the behavior.

**[Expected results]:**
- The process to continue to connect to twitter can be performed.

**[Actual results]:**
- The window freezes.

**[Notes]:**
- Attached is a screen recording of the issue: 
- In some attempts the window froze after the Connect to Twitter prompt was dismissed.
![FreezeTweeter](https://user-images.githubusercontent.com/40061643/143906491-713d795a-3c97-494a-a313-846ef48fe89c.gif)

**Comment by brianpeiris** [comment]
We are working on a fix for this issue in https://github.com/mozilla/reticulum/pull/543 and https://github.com/mozilla/hubs/pull/4997
The fixes will be merged into the qa-stage branches when they are ready.

**Comment by SV-AndreiC** [comment]
I have verified this issue and it's no longer reproducible. The window no longer freezes, however we have discovered another issue related to twitter: https://github.com/mozilla/hubs-cloud/issues/238
