### ISSUE TITLE
mail not set up properly with Recipe #3 on AWS

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs-cloud#28]
I'm using a subdomain (hubs.ieeevr.online) for a domain that is registered on Route 63.

I set up the mail to use the defaults (mail,  ieeevr.online).  Notification mails are not being sent, and if I do an nslookup on mail.ieeevr.online, it doesn't have an ipaddress (which leads me to believe it wasn't configured)?

**Comment by gfodor** [comment]
They’re not in spam I presume? The mail domain doesn’t have an IP it’s just
the reply to domain. Check the Simple Email Service console, you are
probably in the sandbox — there should be a warning in the hubs cloud admin
console. The only email you can send out of the box is the admin email, and
you need to click the verification email you will receive at that address
during stack creation.

**Comment by blairmacintyre** [comment]
Not in spam.  The email address and domain in Simple Email Service console all show verified.

**Comment by gfodor** [comment]
Yeah so are you logging in with the same email you used in the stack
creation form? Until you open a ticket with amazon to leave the sandbox,
you will only be able to send email address. If that’s the case, I’m not
sure what is going on.

**Comment by blairmacintyre** [comment]
Ah, that must be it.  How do I open a ticket to move this?  Remember: “AWS noob here”

---
Blair MacIntyre
Principal Research Scientist

snt frm iOS kybrd, pls pardon typos and weird auto-corrections

blairmacintyre.me && pronoun.is/he/him

________________________________

**Comment by blairmacintyre** [comment]
Ah, found it.  https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

Perhaps add a link to that somewhere.

**Comment by gfodor** [comment]
If you go to the Hubs cloud admin console it should give you info, unless
that broke

**Comment by blairmacintyre** [comment]
Where should I see that in the cloud admin console?

**Comment by gfodor** [comment]
Should pop up on the landing page. If not, just google aws ses sandbox

**Comment by blairmacintyre** [comment]
this page?

![image](https://user-images.githubusercontent.com/1348861/73677198-bdf79180-4683-11ea-8f4b-6ebec123ce55.png)

**Comment by blairmacintyre** [comment]
BTW, I tried applying to get out of the sandbox.  Clearly I didn't utter the right incantation because they said "no, we need more detail."    I'm not sure what to say to them!  Suggestions?

> Hello,
> 
> Thank you for submitting your request to increase your sending limits. We are unable to grant your request at this time because we do not have enough information about your use case.
> 
> If you can provide additional information about how you plan to use Amazon SES, we may be able to grant your request. In your response, include as much detail as you can about your email-sending processes and procedures.
> 
> For example, tell us how often you send email, how you maintain your recipient lists, and how you manage bounces, complaints, and unsubscribe requests. It is also helpful to provide examples of the email you plan to send so we can ensure that you are sending high-quality content.
> 
> You can provide this information by replying to this message. Our team provides an initial response to your request within 24 hours. If we're able to do so, we'll grant your request within this 24-hour period. However, if we need to obtain additional information from you, it might take longer to resolve your request.
> 
> Thank you for contacting Amazon Web Services.
> 
> Best regards,
> 
> Kelsey W.
> Amazon Web Services

**Comment by gfodor** [comment]
Ah yeah, I should probably include some copy about this, you should be able
to tell them you are using SES to send account verification emails of a few
hundred a week and they’ll let you out of the sandbox.

Is the warning not showing up on the hubs admin console?

**Comment by blairmacintyre** [comment]
Aside from the image I sent, what is the "Hubs Admin Console"?

I originally told them:

> Use case description: I've installed an instance of hubs-cloud from Mozilla.  I am using this to support an academic conference (IEEE VR, see ieeevr.org/2020).  As described above, hubs allows users to sign in with their email;  it sends an email when the user supplies it, to confirm they own that email.  That is the only email we will send (in direct response to a user request).
> 
> We expect a few thousand people to use the system, and since the conference is short, I'm requesting a maximum per day that we will hopefully not hit, since most of the attendees will want to register at the same time at the start of the conference.
> 
> Aside from the start of the conference, I don't expect more than a small # per day
> Mail Type: Other
> Website URL: hubs.ieeevr.online
> Describe how you will comply with <a href="http://aws.amazon.com/service-terms/ " target="_blank">AWS Service Terms</a> and <a href="http://aws.amazon.com/aup/ " target="_blank">AUP</a>: 
> Describe how you will only send to recipients who have specifically requested your mail: hubs allows users to sign in with their email;  it sends an email when the user supplies it, to confirm they own that email.  That is the only email we will send (in direct response to a user request)
> Describe the process that you will follow when you receive bounce and complaint notifications:

**Comment by blairmacintyre** [comment]
Ok, I sent them another email.  Will try again.  Worst case, I'll see up my own SMTP server on dreamhost.

Do you know if gmail will let us use them as an SMTP server, since our official email address is on gmail and I'm fine with things appearing to come from it?

**Comment by gfodor** [comment]
Sorry I missed the email. Yep an error should def be there

**Comment by gfodor** [comment]
Not sure about gmail. Probably would be OK for low traffic email
