### ISSUE TITLE
Stack restore results in 502 Bad gateway

### ISSUE THREAD

**Issue by cornelionce** [mozilla/hubs-cloud#292]
[Affected Versions]:

- all

[Affected Platforms]:

- all

[Prerequisites]:

- A stack backup is created and available.

[Steps to reproduce]:

1. Login to aws and go to CloudFormation.
2. Create a stack and fill the details required in the Restore from Backup section.
3. After the stack is created, access your hubs cloud domain.

[Expected results]:

- The stack is restored and the user is able to log to the hubs cloud domain.

[Actual results]:

- The stack is restored correctly (in aws) but when accessing the domain it results in 502  Bad Gateway.

[Notes]:

- Ran into this with a stack created after the May launch and a stack created before that, both resulting in the same bad gateway error (even after 2 hours).

**Comment by Pattersonbl2** [comment]
@cornelionce  Has this issue been fixed or are we still experiencing this issue?

**Comment by cornelionce** [comment]
I can confirm this is no longer reproducing.
