### ISSUE TITLE
Update Python version used in Lambdas by August 2022

### ISSUE THREAD

**Issue by conath** [mozilla/hubs-cloud#296]
There is another Python deprecation coming up on **August 17, 2022** that affects Hubs Cloud. AWS will stop accepting new lambda functions with Python 3.6, and there will be no more security updates for the Python 3.6 runtime. Judging by the last python deprecation #183, after August 17, this might prevent the creation and updates of Hubs Cloud servers on AWS!

In my Hubs Cloud instance these are the functions that use it:

```bash
arn:aws:lambda:my-region:numbers:function:MyServer-CustomAcmCertificateLambda-fPp4uR15lb0C:$LATEST  
arn:aws:lambda:my-region:numbers:function:MyServer-ses-password:$LATEST  
arn:aws:lambda:my-region:numbers:function:MyServer-SESDomainAppli-SESDomainFunction-ypyyEVVR8zrd:$LATEST  
arn:aws:lambda:my-region:numbers:function:MyServer-EmptyBucketFunction-g7Fwlaxw88Tm:$LATEST  
```
I removed my AWS region and server name.

To show which functions are affected on your instance, run this in AWS CLI:

```bash
> aws lambda list-functions --function-version ALL --region YOUR-REGION --output text --query "Functions[?Runtime=='python3.6'].FunctionArn"
```

**Comment by Adi-FHE** [comment]
Is it simply a case of changing * Runtime - Python 3.6 to 3.9 In the AWS Lambda setup?
Or is it required to do some change/updates to our custom client too?

**Comment by Pattersonbl2** [comment]
This has been updated.  AWS lambda is now python3.9.
