### ISSUE TITLE
Cloudflare CORS setup issues

### ISSUE THREAD

**Issue by antpb** [mozilla/hubs-cloud#3]
I'm not able to get the admin generated script to deploy for the CORS Proxy config. In cloudflare I am seeing an error of `Uncaught SyntaxError: Unexpected token '^' at line 9 `

**Steps to error**
1) launch editor from Cloudflare workers page in admin.
2) add script
3) name script "test"
4) Edit script
5) paste script from data transfer admin page. (see below)
6) See "Uncaught SyntaxError: Unexpected token '^' at line 9 "

**Line 9 in the editor is:**
`let targetUrl = request.url.substring(PROXY_HOST.length + 1).replace(/^http(s?):/([^/])/, "http$1://$2");`

Below is a copy of the admin generated code

```
  const ALLOWED_ORIGINS = ["https://brokenplace.com"];
  const PROXY_HOST = "https://undefined";

  addEventListener("fetch", e => {
    const request = e.request;
    const origin = request.headers.get("Origin");
    const proxyUrl = new URL(PROXY_HOST);
    // eslint-disable-next-line no-useless-escape
    let targetUrl = request.url.substring(PROXY_HOST.length + 1).replace(/^http(s?):/([^/])/, "http$1://$2");
    
    if (!targetUrl.startsWith("http://") && !targetUrl.startsWith("https://")) {
      targetUrl = proxyUrl.protocol + "//" + targetUrl;
    }
    
    const requestHeaders = new Headers(request.headers);
    requestHeaders.delete("Origin"); // Some domains disallow access from improper Origins

    e.respondWith((async () => {
      const res = await fetch(targetUrl, { headers: requestHeaders, method: request.method, redirect: "manual", referrer: request.referrer, referrerPolicy: request.referrerPolicy });
      const responseHeaders = new Headers(res.headers);
      const redirectLocation = responseHeaders.get("Location") || responseHeaders.get("location");

      if(redirectLocation) {
        if (!redirectLocation.startsWith("/")) {
          responseHeaders.set("Location",  proxyUrl.protocol + "//" + proxyUrl.host + "/" + redirectLocation);
        } else {
          const tUrl = new URL(targetUrl);
          responseHeaders.set("Location",  proxyUrl.protocol + "//" + proxyUrl.host + "/" + tUrl.origin + redirectLocation);
        }
      }

      if (origin && ALLOWED_ORIGINS.indexOf(origin) >= 0) {
        responseHeaders.set("Access-Control-Allow-Origin", origin);
        responseHeaders.set("Access-Control-Allow-Methods", "GET, HEAD, OPTIONS");
        responseHeaders.set("Access-Control-Allow-Headers", "Range");
        responseHeaders.set("Access-Control-Expose-Headers", "Accept-Ranges, Content-Encoding, Content-Length, Content-Range");
      }

      responseHeaders.set("Vary", "Origin");
      responseHeaders.set('X-Content-Type-Options', "nosniff");

      return new Response(res.body, { status: res.status, statusText: res.statusText, headers: responseHeaders });
    })());
  });
```

If I can give any additional info, let me know. :)

**Comment by gfodor** [comment]
Ah thanks for trying this! I think you are just on an outdated version of the software. To resolve, you can try updating your stack template by going to your stack, clicking "Update", then "Replace" and pointing to `https://hubs-cloud.s3-us-west-1.amazonaws.com/stack.yaml?uncached` and then sanity checking the form. There are probably a small number of form fields you need to fill in that are new.

Also, as I mentioned, this stuff is still very YMMV, so if you are nervous about loss of work doing the stack template replacement, be sure to make a backup of both EFS and the DB. (there are already nightly backups running, but worth sanity checking.) We'll have stack restores from backups working soon, but its not yet implemented.

**Comment by antpb** [comment]
Good to know @gfodor thanks!

I may need to delete the stack and start from scratch. Getting an error when hitting the final "Update Stack" step in the review. 

```
Update of resource type is not permitted. The new template modifies resource type of the following resources: [JanusAndReticulumAdminSecret, ReticulumBotAccessKeySecret, ReticulumOAuthTokenSecret, SendEmailPasswordSecret, PhoenixKeySecret, GuardianSecretKeySecret, ReticulumCookieSecret]
```

**Comment by antpb** [comment]
If I start over, I'll likely need to point nameservers back to AWS and then migrate back over to Cloudflare once it is spun up.

**Comment by gfodor** [comment]
Ah yep, we moved the secrets to a new setup to save $4/mo. I caught some obvious bugs with the external DNS stuff (but still didn't do a full integration test) so you can try taking that for a spin again (where you say "No - My domain is not set up on Route 53")

Template changes should slow down in the next week or so

**Comment by gfodor** [comment]
This should be fixed now, please re-open if you have further issues.
