### ISSUE TITLE
audio settings (fall-off, max distance) for all audio in a room

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs-cloud#32]
I've been thinking about how to design a "poster session" in hubs.  The biggest issue we've had in the past attempts has been audio.  People talking at one poster disturb others;  playing a video at a poster is heard everywhere (effectively).

The easy and simple solution would be to be able to change the entire audio default settings for a room.  For example, I would like to define a relatively short range (20-30m) as the maximum distance for all audio, and also give it less fall off within that range (probably linear from 100% to 75% or so at the edge).

This would have less absolute control over spread than defining regions (e.g., if I put some video to the side of a poster, it might spread further than the voice of the presenter who is standing on the other side), but would perhaps be more intuitive (e.g., if two avatars are 20m apart, they can hear each other regardless of where they are standing).

**Comment by gfodor** [comment]
To address this, I think a good approach would be to expose avatar + media audio settings on the scene node in Spoke.

**Comment by ari-blenkhorn** [comment]
Was this ever addressed? It's certainly still desirable. We're having exactly this concern while running a poster session in hubs for I3D. Thanks!

**Comment by blairmacintyre** [comment]
You can create a scene with custom audio fall off for avatars and media in spoke.  I wrote a blog post about this after VR (https://blairmacintyre.me/2020/04/03/vr2020-design-of-a-poster-room/) and recently did a stream and posted the video showing how to do it for class poster sessions (https://blairmacintyre.me/2020/08/27/setting-up-a-hubs-room-audio-for-a-class-poster-session/)

The online limitation is that if you add media in spoke, they may not get the default media settings (since they take on the settings at the time you drop them in, I think).  But media placed in a room, and avatars, will obey the defaults.

@ari-blenkhorn it's been a long time, hope you're well. you should have asked me!  Hope the poster session went well.

**Comment by ari-blenkhorn** [comment]
@blairmacintyre 
Wish I'd known you were such a resource, I would certainly have come to you in advance!
I wasn't the one who set up the poster session, so I didn't think about these issues until it went live and attendees started asking whether there were user-level controls.
I hope your students got the research data they were after despite the tech hiccups.

I'm involved with an XR symposium at APL in a few months, and I'd like to build on what we've learned from VR, I3D, etc., so I'll be in touch. Thanks!

**Comment by blairmacintyre** [comment]
I didn't realize y'all were using Hubs till a week or so ago, and didn't feel like barging in like a bull in a china shop at that point. :)

Feel free to reach out.

**Comment by misslivirose** [comment]
Closing this since it's captured in issues on the hubs repo
