### ISSUE TITLE
Issues with SMTP configuration (mail not sending)

### ISSUE THREAD

**Issue by LeoRitterVR** [mozilla/hubs-cloud#321]
Hello,

I am opening this post because I am encountering a problem when deploying this solution in a Kubernetes environment.

I based my approach on the tutorial described in this link to perform the operation: https://hubs.mozilla.com/labs/community-edition-case-study-quick-start-on-gcp-w-aws-services/

I am facing an issue when my deployment is finished and I try to connect as an administrator to the hub. Everything appears to be functional visually (no specific errors in the console), however, it seems that the email for connection request is not being sent.

General information:

- I am using Digital Ocean as my Kubernetes provider.
- I am using Mailgun as an SMTP service (tests also conducted with Amazon SES).

Upon inspecting the logs of the Reticulum pod, I found this during the connection attempt: 

![image](https://github.com/mozilla/hubs-cloud/assets/91873315/32dff71a-13fc-4e30-a057-b08132d313c1)

Here is also the configuration of my render_hcce.sh file used during deployment: 

![image](https://github.com/mozilla/hubs-cloud/assets/91873315/5e76f8e7-1d2b-4941-9670-8eb09a4664bc)

I have tried several SMTP services like Mailgun and Amazon SES, and have tested the configurations in another application, so it is unlikely that the SMTP service is at fault here. I also tried to open my 587 port (the one the SMTP service is using), but that didn't changed anything.

Any help regarding a possible mishandling would be greatly appreciated.

**Comment by Doginal** [comment]
run it from where you installed the platform! That will show you if the configs exist then check `kubectl describe secret configs -n hcce` that will show you if each key/value has a pair. then in the pod, echo out the env var you want to see. There is no need to install kubectl in the pods.

**Comment by Arko7777** [comment]
> run it from where you installed the platform! That will show you if the configs exist then check `kubectl describe secret configs -n hcce` which will show you if each key/value has data. Then in the pod, echo out the env var you want to see. There is no need to install kubectl in the pods.

facing same issue, checked all the value + data and echoed all out. smh still not sending the mail.
Any idea what the issue may be?

**Comment by mikemorran** [comment]
Great job @Doginal and @Arko7777
