### ISSUE TITLE
Allow update pausing

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs-cloud#33]
Proposed mechanism for pausing updates:
- Go to admin console, get a magic value that encodes the current version information of all habitat packages
- Go to stack, paste magic value and do a stack update
- Roll the nodes
- Nodes bootstrap script now defers to magic value to determine version to run
- This requires a new AMI bootstrap build which does not have channel bindings burned in

**Comment by misslivirose** [comment]
Closing this since #96 is tracking the same user story
