### ISSUE TITLE
Failed to open scene on hubs which is community edition deployed on Azure

### ISSUE THREAD

**Issue by nakae-giken** [mozilla/hubs-cloud#331]
**Describe the bug**
I deployed community edition on Azure as the instllaction of guide. https://hubs.mozilla.com/labs/installing-mozilla-hubs-community-edition-on-your-own-microsoft-azure-kubernetes-service
And when I tried to open scene, I got the error says "gltf-model-plus.js:51 Releasing uncached gltf #spawn-point" as pasted picture below and failed to load the scene.

**To Reproduce**
1. deploy community edition on Azure as following guild. https://hubs.mozilla.com/labs/installing-mozilla-hubs-community-edition-on-your-own-microsoft-azure-kubernetes-service
2. open scene.

**Expected behavior**
successfully enter the scene

**Screenshots**
![image](https://github.com/mozilla/hubs-cloud/assets/149125347/e6495ce7-fdd4-43ac-b338-227fdb67fb47)

**Desktop (please complete the following information):**
 - OS: Mac OS 14.0（23A344）
 - Browser chrome
 - Version 121.0.6167.139（Official Build） （arm64）

**Comment by mikemorran** [comment]
Hello @nakae-giken, I don't believe this is a bug, more likely it is an issue with your configuration. Are you able to send over your reticulum pod logs when this user attempts to join? Additionally, what kind of scene are you attempting to use? Is this a scene you have created?

**Comment by mikemorran** [comment]
FYI, for help with your deployment, I recommend connecting with me in the #community-edition channel of our discord server

**Comment by nakae-giken** [comment]
@mikemorran 
thanks for your replying!
Actually I could solved this problem few days ago after remake them from first step.
Sorry for that I didn't text that.
But now I have next question so I will go to the channel.

**Comment by mikemorran** [comment]
@nakae-giken glad it got figured out!
