### ISSUE TITLE
[Community Edition] YouTube and Vimeo video links unuseable

### ISSUE THREAD

**Issue by sarurururu** [mozilla/hubs-cloud#333]
**Description**
In Spoke of a Hubs SE instance (on Google Cloud), YouTube and Vimeo URLs cannot be used as the content source of a video element.

**To Reproduce**
1. In Spoke (of Hubs CE), add a video element
2. Specify the YouTube/ Vimeo URL under the "Video" field
3. Spoke tries to load video from the URL

**Expected behavior**
The desired YouTube video is inserted as a video element in the scene.

**Screenshots**
![image](https://github.com/mozilla/hubs-cloud/assets/74574559/19a3d470-ac17-4b99-bf27-2354d7199a9a)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Chrome
 - Version: 122.0.6261.71 (Official Build) (64-bit)

**Comment by mikemorran** [comment]
Hello @sarurururu, thank you for your question. I can't speak for vimeo, however I do know that YouTube is not currently supported on CE. In the past, Hubs had implemented YT support through the YTDownloader tool, however Hubs is avoiding using that moving forward. You could certainly implement it yourself, but be aware that it not within YT's terms of service
