### ISSUE TITLE
"community" link showing as "Join Discord" in hamburger menu

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs-cloud#34]
in the rooms, the hamburger menu on the left has a small "Join Discord" at the bottom that links to the "Community" link.  That should probably say "Community" link the front page (or, there should be a setting to control this label)

**Comment by misslivirose** [comment]
This can be set by changing the text in the admin panel for 'Community Prompt': 
The URL can be changed in the 'Links' tab of the admin panel

![image](https://user-images.githubusercontent.com/4313320/83538337-8ae6d280-a4aa-11ea-9b00-90804c1240dc.png)
