### ISSUE TITLE
account list ignores "rows per page"

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs-cloud#36]
I have 23 accounts;  if rows per page is 10, I'm seeing all 23 records on each of the "3 pages" I can choose from the bottom of the page.

So, it's calculating the number of pages correctly, and letting me select among them, but showing me all 23 records on each page

**Comment by blairmacintyre** [comment]
@brianpeiris @gfodor need this looked at.  Right now I'm at 45 accounts, and it's showing me all of them.  When I load up the reg database and have 500+, it's going to be awful.

Note:  we also need to be able to search by identity, not just ID.  So I can find people.

**Comment by brianpeiris** [comment]
This will be fixed when https://github.com/mozilla/hubs/pull/2196 hits the cloud instances today evening.
