### ISSUE TITLE
is DigitalOcean still supported?

### ISSUE THREAD

**Issue by clpng** [mozilla/hubs-cloud#41]
Hello everyone, 

this documentation page (https://hubs.mozilla.com/docs/hubs-cloud-intro.html) lists DigitalOcean as one of the possible hosting solutions. 
However, the link to further information appears to be broken (HTTP status 500) and there are no other mentioning of digital ocean throughout the docs. 

It DO still supported? If so, where can I find a getting started guide? 

Thanks in advance :)

**Comment by misslivirose** [comment]
Here you go! https://hubs.mozilla.com/docs/hubs-cloud-do-quick-start.html

Please note that this is in very early pre-alpha stages and we anticipating building out the offering in more depth in the coming months.

**Comment by chandeepadissanayake** [comment]
Did you guys do any benchmarking on DigitalOcean Droplets? According to official docs, it says there are no recommendations, but I'm looking for something that can host upto 100 users (Like c5 instance in AWS) - essentially not 100, but ideally yes.
