### ISSUE TITLE
Attempting to delete scenes or accounts from the admin panel signs you out and the scene/avatar is not deleted

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs-cloud#44]
1. Approve a scene in Hubs Cloud instance
2. Try to delete it 

Expected behavior: it deletes
Actual behavior: you get signed out and the scene remains

This happens when the scene is active and in 'removed' state

**Comment by gfodor** [comment]
As of now we don’t have the implementation of content or account deletion.
(Cleaning our all related files, etc.) It should be put on the roadmap.
Scene listings can be set to “unlisted” to effectively remove them, but
scenes themselves are immutable.

**Comment by gfodor** [comment]
Sorry not immutable, but not removable.

**Comment by misslivirose** [comment]
Yeah, since there's a 'Delete' option in the UI, we should make sure that route is clear.

**Comment by misslivirose** [comment]
Also, the feedback in this instance is over concern that it's using storage space on their AWS instance. Is there an alternative way through AWS directly to manage the database contents?

**Comment by gfodor** [comment]
The scene content goes to EFS. They can use the EFS console to see how much
is being used. Unfortunately, there is a lot of work to be done to clean up
unused storage or delete content. We should def prioritize it if we start
getting reports of cost concerns around storage.

**Comment by misslivirose** [comment]
In some cases this results in a 403 instead of a log-out.

**Comment by gfodor** [comment]
Not that useful, but signing out of the admin console is not what's
happening - it's just a glitch in the way we are using react admin. When
you see the sign out or login screen, you still are logged into hubs (and
the admin console) but you landed on a part of react admin we simply don't
use - the bug is that you got to that page (which shouldn't be possible),
not that you got signed out.

**Comment by VirtualConferenceHubs** [comment]
Hi, is there a plan for this enhancement request. Its just annoying when the old scenes/projects are  listed even after you delete them.

**Comment by robin-k-wilson** [comment]
**Ideas and considerations for scene deletion**

**Which menus**
- Can delete scenes in the Admin Panel > Approved scenes
- Can delete projects/scenes in Spoke (todo check if true)

**Considerations**
- Rooms currently referencing this scene
- Spoke vs admin panel scene deletion
- Account has reference to sceneID (todo check if true) 
- Pinned items in room with scene does not get deleted
- Remove reference if re-mixable in Spoke
- If original scene deleted, should remixed scenes in Spoke be deleted as well?

**Admin panel option**
- Click delete button for scene
     - If no room references, "are you sure?" prompt will pop up. 
     - If has room(s) references, a pop up appears with "scene is currently the scene for these rooms" with list of rooms, user can either:
          - "Continue", room(s) now has the default scene assigned
          - "Cancel", user can manually change scene in the room then come back again.

**Comment by misslivirose** [comment]
Going to close this issue and track future work on this going forward in #79
