### ISSUE TITLE
unable to create a room aws

### ISSUE THREAD

**Issue by Fahad-pnw** [mozilla/hubs-cloud#51]
hitting a deadwall after redeploying on aws numerous times with different settings.
i'm on c5.xlarge for application, while stream is on c5.large.
i've setup cdn successfully.

tried various browsers. Now, in another region, its accessible. I'm thinking of some kind of a timing out on this. can anyone help debug or let me know the solution to increase the timeout?

domain: https://[taken-out].com/

**Comment by Fahad-pnw** [comment]
i dont think the CORS issue at top is primarily causing this.
--
its probably unknown error - network scene

**Comment by Fahad-pnw** [comment]
may be altering 90 seconds timeout in hubs.js could fix the bug, any idea..anyone?

**Comment by gfodor** [comment]
Try disabling the CDN worker again

**Comment by Fahad-pnw** [comment]
did that, with/without doesn't fix..

**Comment by gfodor** [comment]
Yes, it is working for me if I create a new room.

**Comment by gfodor** [comment]
It looks like you may be having connectivity issues. You can try updating
your firewall as here:
https://hubs.mozilla.com/docs/hubs-troubleshooting.html#unable-to-connect-error

Or try Chrome, or try a VPN.

**Comment by Fahad-pnw** [comment]
Thanks for the info on the ports.
Is there a possibility to change listening ports on self hosted hubs? could you refer me to the src code?

**Comment by gfodor** [comment]
Unfortunately no way to adjust the port range currently. However, we will
be providing a new stack template in the coming weeks to enable TURN, which
will work around most firewall issues.

**Comment by robin-k-wilson** [comment]
Closing issue, TURN was implemented, doesn't seem to be relevant to the current AWS HC stack.
