### ISSUE TITLE
per room control over access by accounts and other account/room perms

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs-cloud#54]
In addition to being able to restrict access to the server based on accounts, I would like to be able to create rooms that only are accessible from certain accounts.

Essentially, it would be good to have Google-doc like permissions for each room
- accounts with full access (create, modify, etc) (I think the current promoted accounts to this)
- accounts with read-only access (can't change) (I think if we turn edit features off, then this may be the normal)
- explicit access by some people, or anyone with URL (we only do the later;  need to say "only people with explicit perms can access)
- access by those with accounts on server, or anyone with URL (even on servers with "only those with accounts can access, it might be nice to be able to have some "open rooms" that can be shared with others, without requiring accounts)

**Comment by blairmacintyre** [comment]
any update on this?

**Comment by misslivirose** [comment]
Not scheduled yet, but tracking in the main Hubs repo via: https://github.com/mozilla/hubs/issues/3782 since we will likely add this to HMC in the future.
