### ISSUE TITLE
It is difficult to identify what color changes are happening / what to edit when customizing the client

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs-cloud#6]
This might not be something we need to fix in V1, but we should at the very least create a document that explains and shows which element is covered by each color setting in the admin panel. For example, knowing where to change this color: 

![image](https://user-images.githubusercontent.com/4313320/69102838-7d8b5e80-0a18-11ea-85fa-abb9c9ae5827.png)

This could be fixed by a how-to doc that shows each of the color settings with their corresponding element, or perhaps by just having the default color show up in the settings instead of the current black color for each one.

**Comment by misslivirose** [comment]
Update: I did figure out which thing to change to update that label, but I think it would still be good to get a guide in.

**Comment by misslivirose** [comment]
I would self-assign but this seems to be a repo I don't have admin rights to

**Comment by gfodor** [comment]
This is now documented here: https://hubs.mozilla.com/docs/hubs-cloud-customizing-look-and-feel.html
