### ISSUE TITLE
Logo alignment inconsistent

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs-cloud#70]
When you upload a logo it appears left align , and then you have that line of text below it
<img width="949" alt="Screen Shot 2020-06-03 at 8 51 05 PM" src="https://user-images.githubusercontent.com/6835324/83713142-36dc0b00-a5dc-11ea-9df6-04d2781283c7.png">

When you make a room public , the logo becomes aligned to the centre but then that line of text goes away
<img width="947" alt="Screen Shot 2020-06-03 at 8 52 31 PM" src="https://user-images.githubusercontent.com/6835324/83713140-3479b100-a5dc-11ea-82aa-da604ab43d8f.png">

This is a community submitted issue. I redacted the logos/branding as they would not want to share this publicly.

**Comment by misslivirose** [comment]
Duplicate of #119 - Going to resolve this one since the other issue has the CSS included as well, but these images are really helpful! Thanks!
