### ISSUE TITLE
Any plans to open source Hubs Cloud?

### ISSUE THREAD

**Issue by danublue** [mozilla/hubs-cloud#72]
Hi!
Great product! I could not find the source code of the server side of Hubs Cloud. Any plans to make this open source in the future?
Kind regards,
-Tommy

**Comment by jgwinner** [comment]
So it wasn't just me - I was confused at first as the implementation guide was just about setup.

I'd like to see the answer to this too; we were looking at extending some features and the source code would be helpful. (Of course, any base file modifications become open source).

        == John ==

**Comment by jgwinner** [comment]
Or would there be a commercial license?

**Comment by robin-k-wilson** [comment]
Here's your source code for the backed: Server code is Reticulum + Dialog linked at the bottom of the hubs-cloud repo readme: [Dependency Repos](https://github.com/mozilla/hubs-cloud#dependency-repos) + [Hubs-ops (not on there yet)](https://github.com/mozilla/hubs-ops) 

Currently you can deploy a custom client to mess with the frontend code when you deploy Hubs Cloud:  [Custom Clients](https://hubs.mozilla.com/docs/hubs-cloud-custom-clients.html)
We haven't created a way to update the backend (yet) for Hubs Cloud deploys. 

Here's our [Hubs Github Discussions](https://github.com/mozilla/hubs/discussions) thread about self-hosting hubs: [Can I self-host hubs on my own hardware?](https://github.com/mozilla/hubs/discussions/2699)

There is a license when you sign up for Hubs Cloud on AWS or DigitalOcean (alpha).

**Comment by danublue** [comment]
Thank you so much!
