### ISSUE TITLE
Avatar live preview fails to load

### ISSUE THREAD

**Issue by robin-k-wilson** [mozilla/hubs-cloud#83]
Bug: Avatar preview is broken in HC. 
Expected: Should show avatar preview.

Error in console:
`react_devtools_backend.js:6 Failed to load avatar preview TypeError: l.setBasisTextureLoader is not a function`

![image](https://user-images.githubusercontent.com/29560735/87091384-67701f80-c1ee-11ea-89f3-48785ad63adb.png)

**Comment by vjFred** [comment]
i am having the very same issue, could this cause an avatar to fail?

**Comment by robin-k-wilson** [comment]
No this wouldn't. It's just the thumbnail preview. The avatar file is fine.

**Comment by robin-k-wilson** [comment]
We removed the avatar live preview so ... fixed!

**Comment by vjFred** [comment]
Thanks Robin
