### ISSUE TITLE
Importing scenes in Hubs Cloud created with Spoke results in an error loading the project due to the scene camera node missing

### ISSUE THREAD

**Issue by misslivirose** [mozilla/hubs-cloud#98]
![image](https://user-images.githubusercontent.com/4313320/90266107-60998580-de08-11ea-919f-7a42e7a0c478.png)

@robertlong as an FYI - should we hotfix this into the Hubs Cloud client?

**Comment by aziliak** [comment]
Thank you for posting this issue.  I mentioned this issue to Dom during the Friday meetup and he mentioned he might need to hotfix/patch this issue.

**Comment by netpro2k** [comment]
I think this was likely fixed when we last deployed the Spoke update to Hubs Cloud. In general transferring scenes created in Spoke on HMC to Hubs Cloud is not something we are going to support. It will often mostly work, but will break any time new features have been added to HMC and have not yet made it to Hubs Cloud.
