### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by aziliak** [mozilla/hubs-cloud#99]
This really belongs in a Discussion section, but this isn't currently available in this repository (possibly add?)

Has anyone found a good solution for Analytics? The base Google Analytics feature within Hubs Cloud isn't useful at all.

I am wanting the ability to track every room that is within the server. It would be nice to know how many people are in each room and for how long, along with the other Google Analytics information you can normally see. I've seen people mention Open Web Analytics, but not sure I want to go down that route just yet.

Also, if a user goes to a room, the Google Analytics will pick it up for a few minutes and then will show the user as not online, even if they are still within the room.

It seems like the Google Tracking info should automatically be injected when a room is created so this information could be made available.

**Comment by robin-k-wilson** [comment]
https://github.com/mozilla/reticulum/pull/420

Should solve. Will be in next HC release.

**Comment by robin-k-wilson** [comment]
New CSP rules should solve
